name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      run: dotnet build -c Release
    
    - name: Nuget Package
      run: dotnet pack .\\dnpatch\\dnpatch.csproj
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: dnpatch
        # A file, directory or wildcard pattern that describes what to upload
        path: ".\\dnpatch\\bin\\Release\\netstandard2.0\\*.dll"
        
    - name: Upload to nuget.org if it's a new release
      if: startsWith(github.ref, 'refs/tags/')
      shell: pwsh
      run: |
        Get-ChildItem dnpatch\\bin\\Release\\dnlib.*.nupkg | ForEach-Object { dotnet nuget push $_.FullName --api-key ${{secrets.NUGETPACKAGEPAT}}  --source "github" }

    - name: Test
      run: dotnet test --no-build --verbosity normal
